spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eshop
    username: root
    password: rout
  mail:

    username: mailsenderforjava@gmail.com
    password: iltifceckjkwsohf

logging:
  level:
    root: info
  file:
    name: C:\\Users\\User\\IdeaProjects\\eshop\\logs\\eshop-%d{yyyy-MM-dd-HH-mm-ss}.%i.log
  logback:
    rollingpolicy:
      max-file-size: 1MB
eshop:
  picture:
    upload:
      directory: C:\\Users\\User\\IdeaProjects\\eshop\\uploadDirectory