spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eshop
    username: root
    password: rout
  mail:
    host: smtp.gmail.com
    port: 587
    username: mailsenderforjava@gmail.com
    password: iltifceckjkwsohf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath*:db/change-log.xml
logging:
  level:
    root: info
  file:
    name: C:\\Users\\User\\IdeaProjects\\eshop\\logs\\eshop-%d{yyyy-MM-dd-HH-mm-ss}.%i.log
  logback:
    rollingpolicy:
      max-file-size: 1MB
eshop:
  picture:
    upload:
      directory: C:\\Users\\User\\IdeaProjects\\eshop\\uploadDirectory